apiVersion: v1
kind: Service
metadata:
  name: gs-spring-boot
  labels:
    system: spring-boot
    app-grp: test
    app-role: rest
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32001
  selector:
    app: gs-spring-boot
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gs-spring-boot
  labels:
    system: spring-boot
    app-grp: test
    app-role: rest
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gs-spring-boot
    spec:
      containers:
        - image: mycluster.icp:8500/infraees/gs-spring-boot:latest
          imagePullPolicy: Always
          name: gs-spring-boot
          ports:
            - containerPort: 8080
